### ISSUE TITLE
关于转成py3的一点问题

### ISSUE THREAD

**Issue by MashiMaroLjc** [ahonn/Nada#2]
前几天刚好Fork了你的项目，感觉挺有意思，个人想将其从`python2.7`转成`python3.4`,其中有一个问题就是py2中的`sys.setdefaultencoding`被官方移除了，然后去除了这个话，输出的中文又乱码，网上找了很多资料都找不到答案，不知到你是否知道解决方法？

**Comment by ahonn** [comment]
将输出的中文转成 unicode 输出，其实 `sys.setdefaultencoding` 是不建议被使用的。

具体可参考：https://mail.python.org/pipermail//docs/2014-February/017381.html

尝试 reload sys 了么..py3 的话我不是很清楚哦

**Comment by ahonn** [comment]
刚刚查了一下，Python2.7 是默认是 ASCII 编码，所以需要 `sys.setdefaultencoding('utf-8')`，而 Python3 的字符串是Unicode编码。所以讲道理应该是不需要 `sys.setdefaultencoding` 了啊。我刚刚试了一下，也的确是不会乱码。是否在文件头部有加上 `# -*- coding: utf-8 -*-`？

另外提醒你一下，curses 模块不支持windows 哦。

**Comment by MashiMaroLjc** [comment]
curses 模块 可以安装curses-2.2-cp35-none-win_amd64.whl从而在window上使用，不过确实整体效果不太理想。至于乱码的问题，跟`sys.setdefaultencoding('utf-8')`，原因应该是python我设置了了`utf8`，然后`curses.addstr()`里面把它用`gbk`输出了。可是在顶部设置`coding:gbk`，运行又失败……不知道有没有办法设置好`addstr()`的编码……如果不行，我只有看看以后在Linux上行不行了……

**Comment by ahonn** [comment]
建议还是在 *unix 上去搞，毕竟 windows 的话体验也不好。
